### ISSUE TITLE
possibly invalid dois found

### ISSUE THREAD

**Issue by jhpoelen** [PHI-base/data#4]
Hi!
I just stumbled across some funny looking dois in the phi-base_current.csv .
Examples include:

```
10.1073pnas.0711014105
10.1073pnas.0901477106
10.1073ypnas.051624298
10119-24. doi: 10.1073/pnas
� 10.1128/IAI.00011-16
� 10.1074/jbc.M116.752782
� 10.1128/IAI.01190-15
```

**Comment by CuzickA** [comment]
Hi Jorrit,

Many thanks for flagging these dois up. They will be manually corrected in our excel spreadsheet for our future phi4.7 release.

Please let us know if you come across any more doi errors so that they can also be corrected.

FYI, in the future we are planning to capture PHI-base data using an author curation tool which is currently under development called PHI-Canto. This will help to reduce these occasional errors.

**Comment by jhpoelen** [comment]
Hi @CuzickA @martin2urban  - 
Just a reminder that some funny looking DOIs still exist in phi-base_current.tsv (https://github.com/PHI-base/data/commit/79332e332f978bfab429ae3063e067cf0a9dd140) -

| funny DOIs |
| --- |
| 10.1073pnas.0901477106 |
| no data found |
| 10.1073pnas.0711014105 |
| 10.1073ypnas.051624298 |
| <U+200B>10.<U+200B>1105/<U+200B>tpc.<U+200B>12.<U+200B>11.<U+200B>2019 |
| M-2001-0110-03R |

Hope this helps!

**Comment by CuzickA** [comment]
Thanks @jhpoelen that is really helpful. 
Updates will be made for our phi4.7 release due in May 2019.
